// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserInteresting.proto

package com.mtarget.proto.data;

public final class UserInfoProto {
  private UserInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .UserInfo.Age ages = 1;
    java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age> 
        getAgesList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.Age getAges(int index);
    int getAgesCount();
    java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder> 
        getAgesOrBuilderList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder getAgesOrBuilder(
        int index);
    
    // optional int32 gender = 2;
    boolean hasGender();
    int getGender();
    
    // repeated .UserInfo.Tag tags = 3;
    java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> 
        getTagsList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.Tag getTags(int index);
    int getTagsCount();
    java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder> 
        getTagsOrBuilderList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder getTagsOrBuilder(
        int index);
    
    // repeated .UserInfo.Gender genders = 4;
    java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> 
        getGendersList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.Gender getGenders(int index);
    int getGendersCount();
    java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder> 
        getGendersOrBuilderList();
    com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder getGendersOrBuilder(
        int index);
  }
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage
      implements UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(Builder builder) {
      super(builder);
    }
    private UserInfo(boolean noInit) {}
    
    private static final UserInfo defaultInstance;
    public static UserInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_fieldAccessorTable;
    }
    
    public interface TagOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 id = 1;
      boolean hasId();
      int getId();
      
      // required float weight = 2;
      boolean hasWeight();
      float getWeight();
    }
    public static final class Tag extends
        com.google.protobuf.GeneratedMessage
        implements TagOrBuilder {
      // Use Tag.newBuilder() to construct.
      private Tag(Builder builder) {
        super(builder);
      }
      private Tag(boolean noInit) {}
      
      private static final Tag defaultInstance;
      public static Tag getDefaultInstance() {
        return defaultInstance;
      }
      
      public Tag getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Tag_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Tag_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      
      // required float weight = 2;
      public static final int WEIGHT_FIELD_NUMBER = 2;
      private float weight_;
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getWeight() {
        return weight_;
      }
      
      private void initFields() {
        id_ = 0;
        weight_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, weight_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, weight_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Tag parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.mtarget.proto.data.UserInfoProto.UserInfo.Tag prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Tag_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Tag_fieldAccessorTable;
        }
        
        // Construct using com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          weight_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.getDescriptor();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag getDefaultInstanceForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.getDefaultInstance();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag build() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.mtarget.proto.data.UserInfoProto.UserInfo.Tag buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag buildPartial() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag result = new com.mtarget.proto.data.UserInfoProto.UserInfo.Tag(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.weight_ = weight_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mtarget.proto.data.UserInfoProto.UserInfo.Tag) {
            return mergeFrom((com.mtarget.proto.data.UserInfoProto.UserInfo.Tag)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.mtarget.proto.data.UserInfoProto.UserInfo.Tag other) {
          if (other == com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasWeight()) {
            setWeight(other.getWeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasWeight()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                weight_ = input.readFloat();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 id = 1;
        private int id_ ;
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getId() {
          return id_;
        }
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }
        
        // required float weight = 2;
        private float weight_ ;
        public boolean hasWeight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public float getWeight() {
          return weight_;
        }
        public Builder setWeight(float value) {
          bitField0_ |= 0x00000002;
          weight_ = value;
          onChanged();
          return this;
        }
        public Builder clearWeight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          weight_ = 0F;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:UserInfo.Tag)
      }
      
      static {
        defaultInstance = new Tag(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:UserInfo.Tag)
    }
    
    public interface AgeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 id = 1;
      boolean hasId();
      int getId();
      
      // required float weight = 2;
      boolean hasWeight();
      float getWeight();
    }
    public static final class Age extends
        com.google.protobuf.GeneratedMessage
        implements AgeOrBuilder {
      // Use Age.newBuilder() to construct.
      private Age(Builder builder) {
        super(builder);
      }
      private Age(boolean noInit) {}
      
      private static final Age defaultInstance;
      public static Age getDefaultInstance() {
        return defaultInstance;
      }
      
      public Age getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Age_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Age_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      
      // required float weight = 2;
      public static final int WEIGHT_FIELD_NUMBER = 2;
      private float weight_;
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getWeight() {
        return weight_;
      }
      
      private void initFields() {
        id_ = 0;
        weight_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, weight_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, weight_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Age parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.mtarget.proto.data.UserInfoProto.UserInfo.Age prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Age_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Age_fieldAccessorTable;
        }
        
        // Construct using com.mtarget.proto.data.UserInfoProto.UserInfo.Age.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          weight_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Age.getDescriptor();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Age getDefaultInstanceForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Age.getDefaultInstance();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Age build() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.mtarget.proto.data.UserInfoProto.UserInfo.Age buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Age buildPartial() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age result = new com.mtarget.proto.data.UserInfoProto.UserInfo.Age(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.weight_ = weight_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mtarget.proto.data.UserInfoProto.UserInfo.Age) {
            return mergeFrom((com.mtarget.proto.data.UserInfoProto.UserInfo.Age)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.mtarget.proto.data.UserInfoProto.UserInfo.Age other) {
          if (other == com.mtarget.proto.data.UserInfoProto.UserInfo.Age.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasWeight()) {
            setWeight(other.getWeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasWeight()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                weight_ = input.readFloat();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 id = 1;
        private int id_ ;
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getId() {
          return id_;
        }
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }
        
        // required float weight = 2;
        private float weight_ ;
        public boolean hasWeight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public float getWeight() {
          return weight_;
        }
        public Builder setWeight(float value) {
          bitField0_ |= 0x00000002;
          weight_ = value;
          onChanged();
          return this;
        }
        public Builder clearWeight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          weight_ = 0F;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:UserInfo.Age)
      }
      
      static {
        defaultInstance = new Age(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:UserInfo.Age)
    }
    
    public interface GenderOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 id = 1;
      boolean hasId();
      int getId();
      
      // required float weight = 2;
      boolean hasWeight();
      float getWeight();
    }
    public static final class Gender extends
        com.google.protobuf.GeneratedMessage
        implements GenderOrBuilder {
      // Use Gender.newBuilder() to construct.
      private Gender(Builder builder) {
        super(builder);
      }
      private Gender(boolean noInit) {}
      
      private static final Gender defaultInstance;
      public static Gender getDefaultInstance() {
        return defaultInstance;
      }
      
      public Gender getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Gender_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Gender_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      
      // required float weight = 2;
      public static final int WEIGHT_FIELD_NUMBER = 2;
      private float weight_;
      public boolean hasWeight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getWeight() {
        return weight_;
      }
      
      private void initFields() {
        id_ = 0;
        weight_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasWeight()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, weight_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, weight_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.mtarget.proto.data.UserInfoProto.UserInfo.Gender parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.mtarget.proto.data.UserInfoProto.UserInfo.Gender prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Gender_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_Gender_fieldAccessorTable;
        }
        
        // Construct using com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          weight_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.getDescriptor();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender getDefaultInstanceForType() {
          return com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.getDefaultInstance();
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender build() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.mtarget.proto.data.UserInfoProto.UserInfo.Gender buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender buildPartial() {
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender result = new com.mtarget.proto.data.UserInfoProto.UserInfo.Gender(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.weight_ = weight_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mtarget.proto.data.UserInfoProto.UserInfo.Gender) {
            return mergeFrom((com.mtarget.proto.data.UserInfoProto.UserInfo.Gender)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.mtarget.proto.data.UserInfoProto.UserInfo.Gender other) {
          if (other == com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasWeight()) {
            setWeight(other.getWeight());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasWeight()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                weight_ = input.readFloat();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 id = 1;
        private int id_ ;
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getId() {
          return id_;
        }
        public Builder setId(int value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          onChanged();
          return this;
        }
        
        // required float weight = 2;
        private float weight_ ;
        public boolean hasWeight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public float getWeight() {
          return weight_;
        }
        public Builder setWeight(float value) {
          bitField0_ |= 0x00000002;
          weight_ = value;
          onChanged();
          return this;
        }
        public Builder clearWeight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          weight_ = 0F;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:UserInfo.Gender)
      }
      
      static {
        defaultInstance = new Gender(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:UserInfo.Gender)
    }
    
    private int bitField0_;
    // repeated .UserInfo.Age ages = 1;
    public static final int AGES_FIELD_NUMBER = 1;
    private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age> ages_;
    public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age> getAgesList() {
      return ages_;
    }
    public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder> 
        getAgesOrBuilderList() {
      return ages_;
    }
    public int getAgesCount() {
      return ages_.size();
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.Age getAges(int index) {
      return ages_.get(index);
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder getAgesOrBuilder(
        int index) {
      return ages_.get(index);
    }
    
    // optional int32 gender = 2;
    public static final int GENDER_FIELD_NUMBER = 2;
    private int gender_;
    public boolean hasGender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getGender() {
      return gender_;
    }
    
    // repeated .UserInfo.Tag tags = 3;
    public static final int TAGS_FIELD_NUMBER = 3;
    private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> tags_;
    public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> getTagsList() {
      return tags_;
    }
    public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    public int getTagsCount() {
      return tags_.size();
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag getTags(int index) {
      return tags_.get(index);
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }
    
    // repeated .UserInfo.Gender genders = 4;
    public static final int GENDERS_FIELD_NUMBER = 4;
    private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> genders_;
    public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> getGendersList() {
      return genders_;
    }
    public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder> 
        getGendersOrBuilderList() {
      return genders_;
    }
    public int getGendersCount() {
      return genders_.size();
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender getGenders(int index) {
      return genders_.get(index);
    }
    public com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder getGendersOrBuilder(
        int index) {
      return genders_.get(index);
    }
    
    private void initFields() {
      ages_ = java.util.Collections.emptyList();
      gender_ = 0;
      tags_ = java.util.Collections.emptyList();
      genders_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getAgesCount(); i++) {
        if (!getAges(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTagsCount(); i++) {
        if (!getTags(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getGendersCount(); i++) {
        if (!getGenders(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ages_.size(); i++) {
        output.writeMessage(1, ages_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, gender_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(3, tags_.get(i));
      }
      for (int i = 0; i < genders_.size(); i++) {
        output.writeMessage(4, genders_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < ages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, ages_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, gender_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, tags_.get(i));
      }
      for (int i = 0; i < genders_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, genders_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.mtarget.proto.data.UserInfoProto.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mtarget.proto.data.UserInfoProto.UserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mtarget.proto.data.UserInfoProto.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mtarget.proto.data.UserInfoProto.internal_static_UserInfo_fieldAccessorTable;
      }
      
      // Construct using com.mtarget.proto.data.UserInfoProto.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAgesFieldBuilder();
          getTagsFieldBuilder();
          getGendersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (agesBuilder_ == null) {
          ages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          agesBuilder_.clear();
        }
        gender_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          tagsBuilder_.clear();
        }
        if (gendersBuilder_ == null) {
          genders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          gendersBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mtarget.proto.data.UserInfoProto.UserInfo.getDescriptor();
      }
      
      public com.mtarget.proto.data.UserInfoProto.UserInfo getDefaultInstanceForType() {
        return com.mtarget.proto.data.UserInfoProto.UserInfo.getDefaultInstance();
      }
      
      public com.mtarget.proto.data.UserInfoProto.UserInfo build() {
        com.mtarget.proto.data.UserInfoProto.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.mtarget.proto.data.UserInfoProto.UserInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.mtarget.proto.data.UserInfoProto.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.mtarget.proto.data.UserInfoProto.UserInfo buildPartial() {
        com.mtarget.proto.data.UserInfoProto.UserInfo result = new com.mtarget.proto.data.UserInfoProto.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (agesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            ages_ = java.util.Collections.unmodifiableList(ages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ages_ = ages_;
        } else {
          result.ages_ = agesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.gender_ = gender_;
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        if (gendersBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            genders_ = java.util.Collections.unmodifiableList(genders_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.genders_ = genders_;
        } else {
          result.genders_ = gendersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mtarget.proto.data.UserInfoProto.UserInfo) {
          return mergeFrom((com.mtarget.proto.data.UserInfoProto.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.mtarget.proto.data.UserInfoProto.UserInfo other) {
        if (other == com.mtarget.proto.data.UserInfoProto.UserInfo.getDefaultInstance()) return this;
        if (agesBuilder_ == null) {
          if (!other.ages_.isEmpty()) {
            if (ages_.isEmpty()) {
              ages_ = other.ages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAgesIsMutable();
              ages_.addAll(other.ages_);
            }
            onChanged();
          }
        } else {
          if (!other.ages_.isEmpty()) {
            if (agesBuilder_.isEmpty()) {
              agesBuilder_.dispose();
              agesBuilder_ = null;
              ages_ = other.ages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              agesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAgesFieldBuilder() : null;
            } else {
              agesBuilder_.addAllMessages(other.ages_);
            }
          }
        }
        if (other.hasGender()) {
          setGender(other.getGender());
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000004);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        if (gendersBuilder_ == null) {
          if (!other.genders_.isEmpty()) {
            if (genders_.isEmpty()) {
              genders_ = other.genders_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureGendersIsMutable();
              genders_.addAll(other.genders_);
            }
            onChanged();
          }
        } else {
          if (!other.genders_.isEmpty()) {
            if (gendersBuilder_.isEmpty()) {
              gendersBuilder_.dispose();
              gendersBuilder_ = null;
              genders_ = other.genders_;
              bitField0_ = (bitField0_ & ~0x00000008);
              gendersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGendersFieldBuilder() : null;
            } else {
              gendersBuilder_.addAllMessages(other.genders_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getAgesCount(); i++) {
          if (!getAges(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getTagsCount(); i++) {
          if (!getTags(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getGendersCount(); i++) {
          if (!getGenders(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder subBuilder = com.mtarget.proto.data.UserInfoProto.UserInfo.Age.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAges(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              gender_ = input.readInt32();
              break;
            }
            case 26: {
              com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder subBuilder = com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTags(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder subBuilder = com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGenders(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .UserInfo.Age ages = 1;
      private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age> ages_ =
        java.util.Collections.emptyList();
      private void ensureAgesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ages_ = new java.util.ArrayList<com.mtarget.proto.data.UserInfoProto.UserInfo.Age>(ages_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder> agesBuilder_;
      
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age> getAgesList() {
        if (agesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ages_);
        } else {
          return agesBuilder_.getMessageList();
        }
      }
      public int getAgesCount() {
        if (agesBuilder_ == null) {
          return ages_.size();
        } else {
          return agesBuilder_.getCount();
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Age getAges(int index) {
        if (agesBuilder_ == null) {
          return ages_.get(index);
        } else {
          return agesBuilder_.getMessage(index);
        }
      }
      public Builder setAges(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Age value) {
        if (agesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgesIsMutable();
          ages_.set(index, value);
          onChanged();
        } else {
          agesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAges(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder builderForValue) {
        if (agesBuilder_ == null) {
          ensureAgesIsMutable();
          ages_.set(index, builderForValue.build());
          onChanged();
        } else {
          agesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAges(com.mtarget.proto.data.UserInfoProto.UserInfo.Age value) {
        if (agesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgesIsMutable();
          ages_.add(value);
          onChanged();
        } else {
          agesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAges(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Age value) {
        if (agesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgesIsMutable();
          ages_.add(index, value);
          onChanged();
        } else {
          agesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAges(
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder builderForValue) {
        if (agesBuilder_ == null) {
          ensureAgesIsMutable();
          ages_.add(builderForValue.build());
          onChanged();
        } else {
          agesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAges(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder builderForValue) {
        if (agesBuilder_ == null) {
          ensureAgesIsMutable();
          ages_.add(index, builderForValue.build());
          onChanged();
        } else {
          agesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAges(
          java.lang.Iterable<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.Age> values) {
        if (agesBuilder_ == null) {
          ensureAgesIsMutable();
          super.addAll(values, ages_);
          onChanged();
        } else {
          agesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAges() {
        if (agesBuilder_ == null) {
          ages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          agesBuilder_.clear();
        }
        return this;
      }
      public Builder removeAges(int index) {
        if (agesBuilder_ == null) {
          ensureAgesIsMutable();
          ages_.remove(index);
          onChanged();
        } else {
          agesBuilder_.remove(index);
        }
        return this;
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder getAgesBuilder(
          int index) {
        return getAgesFieldBuilder().getBuilder(index);
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder getAgesOrBuilder(
          int index) {
        if (agesBuilder_ == null) {
          return ages_.get(index);  } else {
          return agesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder> 
           getAgesOrBuilderList() {
        if (agesBuilder_ != null) {
          return agesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ages_);
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder addAgesBuilder() {
        return getAgesFieldBuilder().addBuilder(
            com.mtarget.proto.data.UserInfoProto.UserInfo.Age.getDefaultInstance());
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder addAgesBuilder(
          int index) {
        return getAgesFieldBuilder().addBuilder(
            index, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.getDefaultInstance());
      }
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder> 
           getAgesBuilderList() {
        return getAgesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Age, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder> 
          getAgesFieldBuilder() {
        if (agesBuilder_ == null) {
          agesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mtarget.proto.data.UserInfoProto.UserInfo.Age, com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.AgeOrBuilder>(
                  ages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          ages_ = null;
        }
        return agesBuilder_;
      }
      
      // optional int32 gender = 2;
      private int gender_ ;
      public boolean hasGender() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getGender() {
        return gender_;
      }
      public Builder setGender(int value) {
        bitField0_ |= 0x00000002;
        gender_ = value;
        onChanged();
        return this;
      }
      public Builder clearGender() {
        bitField0_ = (bitField0_ & ~0x00000002);
        gender_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .UserInfo.Tag tags = 3;
      private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tags_ = new java.util.ArrayList<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag>(tags_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder> tagsBuilder_;
      
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      public Builder setTags(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTags(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTags(com.mtarget.proto.data.UserInfoProto.UserInfo.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTags(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTags(
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTags(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTags(
          java.lang.Iterable<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.Tag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          super.addAll(values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.getDefaultInstance());
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.getDefaultInstance());
      }
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Tag, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mtarget.proto.data.UserInfoProto.UserInfo.Tag, com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.TagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      
      // repeated .UserInfo.Gender genders = 4;
      private java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> genders_ =
        java.util.Collections.emptyList();
      private void ensureGendersIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          genders_ = new java.util.ArrayList<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender>(genders_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder> gendersBuilder_;
      
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> getGendersList() {
        if (gendersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(genders_);
        } else {
          return gendersBuilder_.getMessageList();
        }
      }
      public int getGendersCount() {
        if (gendersBuilder_ == null) {
          return genders_.size();
        } else {
          return gendersBuilder_.getCount();
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender getGenders(int index) {
        if (gendersBuilder_ == null) {
          return genders_.get(index);
        } else {
          return gendersBuilder_.getMessage(index);
        }
      }
      public Builder setGenders(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender value) {
        if (gendersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGendersIsMutable();
          genders_.set(index, value);
          onChanged();
        } else {
          gendersBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setGenders(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder builderForValue) {
        if (gendersBuilder_ == null) {
          ensureGendersIsMutable();
          genders_.set(index, builderForValue.build());
          onChanged();
        } else {
          gendersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addGenders(com.mtarget.proto.data.UserInfoProto.UserInfo.Gender value) {
        if (gendersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGendersIsMutable();
          genders_.add(value);
          onChanged();
        } else {
          gendersBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addGenders(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender value) {
        if (gendersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGendersIsMutable();
          genders_.add(index, value);
          onChanged();
        } else {
          gendersBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addGenders(
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder builderForValue) {
        if (gendersBuilder_ == null) {
          ensureGendersIsMutable();
          genders_.add(builderForValue.build());
          onChanged();
        } else {
          gendersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addGenders(
          int index, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder builderForValue) {
        if (gendersBuilder_ == null) {
          ensureGendersIsMutable();
          genders_.add(index, builderForValue.build());
          onChanged();
        } else {
          gendersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllGenders(
          java.lang.Iterable<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.Gender> values) {
        if (gendersBuilder_ == null) {
          ensureGendersIsMutable();
          super.addAll(values, genders_);
          onChanged();
        } else {
          gendersBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearGenders() {
        if (gendersBuilder_ == null) {
          genders_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          gendersBuilder_.clear();
        }
        return this;
      }
      public Builder removeGenders(int index) {
        if (gendersBuilder_ == null) {
          ensureGendersIsMutable();
          genders_.remove(index);
          onChanged();
        } else {
          gendersBuilder_.remove(index);
        }
        return this;
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder getGendersBuilder(
          int index) {
        return getGendersFieldBuilder().getBuilder(index);
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder getGendersOrBuilder(
          int index) {
        if (gendersBuilder_ == null) {
          return genders_.get(index);  } else {
          return gendersBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder> 
           getGendersOrBuilderList() {
        if (gendersBuilder_ != null) {
          return gendersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(genders_);
        }
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder addGendersBuilder() {
        return getGendersFieldBuilder().addBuilder(
            com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.getDefaultInstance());
      }
      public com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder addGendersBuilder(
          int index) {
        return getGendersFieldBuilder().addBuilder(
            index, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.getDefaultInstance());
      }
      public java.util.List<com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder> 
           getGendersBuilderList() {
        return getGendersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.mtarget.proto.data.UserInfoProto.UserInfo.Gender, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder> 
          getGendersFieldBuilder() {
        if (gendersBuilder_ == null) {
          gendersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.mtarget.proto.data.UserInfoProto.UserInfo.Gender, com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder, com.mtarget.proto.data.UserInfoProto.UserInfo.GenderOrBuilder>(
                  genders_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          genders_ = null;
        }
        return gendersBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:UserInfo)
    }
    
    static {
      defaultInstance = new UserInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:UserInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_Tag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInfo_Tag_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_Age_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInfo_Age_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_Gender_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserInfo_Gender_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025UserInteresting.proto\"\343\001\n\010UserInfo\022\033\n\004" +
      "ages\030\001 \003(\0132\r.UserInfo.Age\022\016\n\006gender\030\002 \001(" +
      "\005\022\033\n\004tags\030\003 \003(\0132\r.UserInfo.Tag\022!\n\007gender" +
      "s\030\004 \003(\0132\020.UserInfo.Gender\032!\n\003Tag\022\n\n\002id\030\001" +
      " \002(\005\022\016\n\006weight\030\002 \002(\002\032!\n\003Age\022\n\n\002id\030\001 \002(\005\022" +
      "\016\n\006weight\030\002 \002(\002\032$\n\006Gender\022\n\n\002id\030\001 \002(\005\022\016\n" +
      "\006weight\030\002 \002(\002B)\n\026com.mtarget.proto.dataB" +
      "\rUserInfoProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_UserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_UserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserInfo_descriptor,
              new java.lang.String[] { "Ages", "Gender", "Tags", "Genders", },
              com.mtarget.proto.data.UserInfoProto.UserInfo.class,
              com.mtarget.proto.data.UserInfoProto.UserInfo.Builder.class);
          internal_static_UserInfo_Tag_descriptor =
            internal_static_UserInfo_descriptor.getNestedTypes().get(0);
          internal_static_UserInfo_Tag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserInfo_Tag_descriptor,
              new java.lang.String[] { "Id", "Weight", },
              com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.class,
              com.mtarget.proto.data.UserInfoProto.UserInfo.Tag.Builder.class);
          internal_static_UserInfo_Age_descriptor =
            internal_static_UserInfo_descriptor.getNestedTypes().get(1);
          internal_static_UserInfo_Age_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserInfo_Age_descriptor,
              new java.lang.String[] { "Id", "Weight", },
              com.mtarget.proto.data.UserInfoProto.UserInfo.Age.class,
              com.mtarget.proto.data.UserInfoProto.UserInfo.Age.Builder.class);
          internal_static_UserInfo_Gender_descriptor =
            internal_static_UserInfo_descriptor.getNestedTypes().get(2);
          internal_static_UserInfo_Gender_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_UserInfo_Gender_descriptor,
              new java.lang.String[] { "Id", "Weight", },
              com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.class,
              com.mtarget.proto.data.UserInfoProto.UserInfo.Gender.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
