package com.mtarget.mapred;

public interface Constant {
	String HOST_PATH = "HOST_PATH";
	String REGION = "REGION";
	String REDIS_NAME = "REDIS_NAME";
	String TRY_TIMES = "TRY_TIMES";
	String CONFIG_PATH = "CONFIG_PATH";
	String TAG_PROPERTIES = "tags.properties";
	String USER_MAP_ATTRIBUTE_PROPERTIES = "UserAttrMap.properties";
	String RFT = "RFT";
	String REQUEST_URL = "REQUEST_URL";
	String OUTPUT_COLUMN = "OUTPUT_COLUMN";
	String OUTPUT_TABLE = "OUTPUT_TABLE";
	String HBASE_CONFIG = "HBASE_CONFIG";
	String COLUMN_LIST = "COLUMN_LIST";
	String CHARSET = "CHARSET";
	Integer TRY_TIMES_NUM = 2;
	String PUBLISHER_URL_REGEX="urlFilter.properties";
	int    DEFAULT_USER_TAG_THRESHOLD=10;
	String USER_TAG_THRESHOLD="USER_TAG_THRESHOLD";
	int DEFAULT_URL_TAG_THRESHOLD=10;
	String URL_TAG_THRESHOLD="URL_TAG_THRESHOLD";
	String JEDIS_USER_EXPIRED="JEDIS_USER_EXPIRED";
	String JEDIS_URL_EXPIRED="JEDIS_URL_EXPIRED";
	int DEFAULT_REDIS_EXPIRE_SECONDS = 86400;
	String HBASE_EXPIRED_TIME="HBASE_EXPIRED_TIME";//hour
	String HBASE_EXPIRED_UNIT="HBASE_EXPIRED_UNIT";//过期计算单位D-天, H-小时
	long DEFAULT_HBASE_EXPIRED_TIME=0;
}
